version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - "> 3.6.4, < 3.7"
  - dependency-name: eslint-plugin-vue
    versions:
    - "> 6.2.1, < 6.3"
  - dependency-name: firebase
    versions:
    - "> 7.14.2, < 7.15"
  - dependency-name: firebase
    versions:
    - "> 7.15.3, < 7.16"
  - dependency-name: firebase
    versions:
    - "> 7.6.0, < 7.7"
  - dependency-name: firebase
    versions:
    - "> 7.9.0, < 7.10"
  - dependency-name: firebase
    versions:
    - "> 8.2.1, < 8.3"
  - dependency-name: graphql-tag
    versions:
    - "> 2.10.3, < 2.11"
  - dependency-name: sass
    versions:
    - "> 1.26.2, < 1.27"
  - dependency-name: sass
    versions:
    - "> 1.32.2, < 1.33"
  - dependency-name: sass-loader
    versions:
    - "> 10.0.1, < 10.1"
  - dependency-name: sass-loader
    versions:
    - "> 10.1.0, < 10.2"
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - "> 4.2.2, < 4.3"
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - "> 4.4.1, < 4.5"
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - "> 4.2.2, < 4.3"
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - "> 4.4.1, < 4.5"
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - "> 4.5.10, < 4.6"
  - dependency-name: "@vue/cli-service"
    versions:
    - "> 4.2.2, < 4.3"
  - dependency-name: "@vue/cli-service"
    versions:
    - "> 4.4.1, < 4.5"
  - dependency-name: "@vue/cli-service"
    versions:
    - "> 4.5.10, < 4.6"
  - dependency-name: vue-router
    versions:
    - "> 3.1.5, < 3.2"
  - dependency-name: vue-router
    versions:
    - "> 3.3.2, < 3.4"
  - dependency-name: vuetify
    versions:
    - "> 2.3.8, < 2.4"
  - dependency-name: vuetify
    versions:
    - "> 2.4.2, < 2.5"
